[package]
name = "api-call"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
serde = { version="1.0.23", features = ["derive"]}
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
